### ISSUE TITLE
Why does the program always stop automatically? The longest one only ran to 700. Maybe you can help me crack this?

### ISSUE THREAD

**Issue by mokuseisama** [GuangPingLin/BaiduNetdiskFetchCodeCrack#1]
Why does the program always stop automatically（at 7cmn）>_<? The longest one only ran to 700. Maybe you can help me crack this?（https://pan.baidu.com/s/19MZSvIk-d9CNDUqu6rU2SQ）Thanks Orz，Orz，Orz

**Comment by GuangPingLin** [comment]
Hello, have you configurated your own http proxy? If not, it is because the http proxy that i provide has run out

**Comment by mokuseisama** [comment]
Not yet. Thanks,now I already know what the problem is. I'll try again later
